name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout miniRT
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: sudo apt-get install -y libx11-dev libxext-dev libbsd-dev libxrandr-dev libxpm-dev libxft-dev libxinerama-dev libxcursor-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev

      - name: Norminette
        run: |
          pip3 install norminette
          make norm

      - name: Build
        run: make